self.addEventListener('install',()=>self.skipWaiting());
self.addEventListener('activate',event=>{
  event.waitUntil(
    caches.keys()
      .then(keys=>Promise.all(keys.filter(k=>[
        'dysphagia-pwa-v2.3',
        'dysphagia-scale-drill-pwa-v2',
        'dysphagia-scale-drill-pwa-v3'
      ].includes(k)).map(k=>caches.delete(k))))
      .then(()=>self.registration.unregister())
      .then(()=>self.clients.claim())
  );
});